name: Test SSH to EC2

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SSH to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Hello from GitHub Actions"