name: streamlit_cicd

on:
  push:
    paths:
      -'streamlit/app.py'
    
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build and Restart Docker
        run: |
          cd /home/ubuntu/streamlit/Dockerfile
          docker build -t bitcoin-ui .
          docker run -p 80:8501 bitcoin-ui